version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study_pupunit
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    ports:
      - 9000:9000
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
